M48
; DRILL file {KiCad (6.0.5-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-04T23:20:25+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X5.2146Y-4.5836
X5.3051Y-4.5836
T2
X4.9902Y-4.5965
X5.5295Y-4.59
T0
M30
