M48
; DRILL file {KiCad (6.0.5-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-18T01:32:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X5.2146Y-4.6033
X5.3051Y-4.6033
T2
X4.9902Y-4.6161
X5.5295Y-4.6161
T0
M30
